---
version: "2"
services:
  vaapi-video-converter:
    image: jrottenberg/ffmpeg:vaapi
    container_name: vaapi-video-converter
    environment:
      - VIDEO_BITRATE=1280k
      - VIDEO_CODEC=h264_vaapi
      - VIDEO_WIDTH=720
      - AUDIO_BITRATE=128k
      - AUDIO_CODEC=aac
      - AUDIO_CHANNELS=2
      - AUDIO_LANGUAGES=deu,ger,eng
      - VAAPI_DEVICE=/dev/dri/renderD128
    volumes:
      - ./entrypoint:/entrypoint:ro
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    group_add:
      - video
    entrypoint: [ "/entrypoint" ]
