#!/bin/sh

[ -z "$2" -o ! -f "$1" ] && echo "Syntax: $(basename $0) <input-file> <output-file>" && return 1

in_fullpath=$(realpath "$1")
in_dir_host=$(dirname  "$in_fullpath")
in_file=$(    basename "$in_fullpath")
out_fullpath=$(realpath "$2")
out_dir_host=$(dirname  "$out_fullpath")
out_file=$(    basename "$out_fullpath")
in_dir_container='/video/in'
out_dir_container='/video/out'
env_args=''
env_args="${env_args} -e PUID=${PUID:-$(id -u)}"
env_args="${env_args} -e PGID=${PGID:-$(id -g)}"
[ "${VIDEO_CODEC}"    ] && env_args="${env_args} -e VIDEO_CODEC=${VIDEO_CODEC}"
[ "${VIDEO_BITRATE}"  ] && env_args="${env_args} -e VIDEO_BITRATE=${VIDEO_BITRATE}"
[ "${VIDEO_WIDTH}"    ] && env_args="${env_args} -e VIDEO_WIDTH=${VIDEO_WIDTH}"
[ "${AUDIO_CODEC}"    ] && env_args="${env_args} -e AUDIO_CODEC=${AUDIO_CODEC}"
[ "${AUDIO_BITRATE}"  ] && env_args="${env_args} -e AUDIO_BITRATE=${AUDIO_BITRATE}"
[ "${AUDIO_CHANNELS}" ] && env_args="${env_args} -e AUDIO_CHANNELS=${AUDIO_CHANNELS}"
[ "${AUDIO_LANGUAGE}" ] && env_args="${env_args} -e LANGUAGE=${AUDIO_LANGUAGE}"
[ "${VAAPI_DEVICE}"   ] && env_args="${env_args} -e VAAPI_DEVICE=${VAAPI_DEVICE}"

docker-compose run --rm                      \
  -v "${in_dir_host}:${in_dir_container}:ro" \
  -v "${out_dir_host}:${out_dir_container}"  \
  $env_args                                  \
  video-conversion                           \
  "${in_dir_container}/${in_file}"           \
  "${out_dir_container}/${out_file}"
